builds:
  - main: ./cmd/k8s-configurator/main.go
    binary: k8s-configurator
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
brew:
  # Reporitory to push the tap to.
  github:
    owner: namely
    name: homebrew-tap

  # Allows you to set a custom download strategy.
  # Default is empty.
  download_strategy: CustomDownloadStrategies::GitHubPrivateRepositoryReleaseDownloadStrategy

  # Add custom require_relative to include download strategy
  # Default is empty.
  custom_require: ../github_download_strategy

  # Git author used to commit to the repository.
  # Defaults are shown.
  commit_author:
    name: goreleaserbot
    email: goreleaser@namely.com

  # Folder inside the repository to put the formula.
  # Default is the root folder.
  folder: Formula

  # Your app's homepage.
  # Default is empty.
  homepage: "https://github.com/namely/k8s-configurator"

  # Your app's description.
  # Default is empty.
  description: "k8s-configurator generates environment specific configs from a single source."
